### ISSUE TITLE
Kubernetes (K8s)

### ISSUE THREAD

**Issue by nicholasjhenry** [nicholasjhenry/technology-radar#3]
> an open-source system for automating deployment, scaling, and management of containerized applications.

https://kubernetes.io

## Links

- https://github.com/nicholasjhenry/kubernetes-playground
- https://www.theguild.nl/real-world-phoenix-lets-d4y-using-k8s/
- https://www.digitalocean.com/community/tutorials/how-to-develop-applications-on-kubernetes-with-okteto

## Plan

- [ ] Read https://kubectl.docs.kubernetes.io
- [ ] Create a minimum Phoenix app with no Ecto/Webpack etc and deploy to Digital Ocean Kubernetes cluster.

## Concepts

https://kubernetes.io/docs/concepts/

- Overview
  - [x] What is Kubernetes?
  - [x] Kubernetes Components
  - [x] The Kubernetes API
  - [x] Working with Kubernetes Objects
    - [x] Understanding Kubernetes Objects
    - [x] Kubernetes Object Management
    - [x] Object Names and IDs
    - [x] Namespaces
    - [x] Labels and Selectors
    - [x] Annotations
    - [x] Field Selectors
    - [x] Recommended Labels
- Cluster Architecture
  - [ ] Nodes
  - [ ] Control Plane-Node Communication
  - [ ] Controllers
  - [ ] Cloud Controller Manager
- Containers
  - [ ] Containers overview
  - [ ] Images
  - [ ] Container Environment
  - [ ] Runtime Class
  - [ ] Container Lifecycle Hooks
- Services, Load Balancing, and Networking
    - [ ] Service
    - [ ] Service Topology
    - [ ] EndpointSlices
    - [ ] DNS for Services and Pods
    - [ ] Connecting Applications with Services
    - [ ] Ingress
    - [ ] Ingress Controllers
    - [ ] Network Policies
    - [ ] Adding entries to Pod /etc/hosts with HostAliases
    - [ ] IPv4/IPv6 dual-stack
- Storage
  - [ ] Volumes
  - [ ] Persistent Volumes
  - [ ] Volume Snapshots
  - [ ] CSI Volume Cloning
  - [ ] Storage Classes
  - [ ] Volume Snapshot Classes
  - [ ] Dynamic Volume Provisioning
  - [ ] Node-specific Volume Limits
- Configuration
  - [ ] Configuration Best Practices
  - [ ] ConfigMaps
  - [ ] Secrets
  - [ ] Managing Resources for Containers
  - [ ] Pod Overhead
  - [ ] Resource Bin Packing for Extended Resources
  - [ ] Organizing Cluster Access Using kubeconfig Files
  - [ ] Pod Priority and Preemption
- Security
  - [ ] Overview of Cloud Native Security
  - [ ] Pod Security Standards
- Policies
  - [ ] Limit Ranges
  - [ ] Resource Quotas
  - [ ] Pod Security Policies
- Scheduling and Eviction
  - [ ] Kubernetes Scheduler
  - [ ] Taints and Tolerations
  - [ ] Assigning Pods to Nodes
  - [ ] Scheduling Framework
  - [ ] Scheduler Performance Tuning

## Tasks

https://kubernetes.io/docs/tasks/

- [ ] Configure Pods and Containers
- [ ] Manage Kubernetes Objects
- [ ] Inject Data Into Applications
- [ ] Run Applications
- [ ] Run Jobs
- [ ] Access Applications in a Cluster
- [ ] Monitoring, Logging, and Debugging

**Comment by nicholasjhenry** [comment]
Completed [Tutorial Clueful Elixir with Kubernetes](https://www.erlang-solutions.com/training/tutorial-clueful-elixir-with-kubernetes.html) at ElixirConf EU 2020.

**Comment by nicholasjhenry** [comment]
Completed [How To Develop Applications on Kubernetes with Okteto](https://github.com/nicholasjhenry/hello-kubernetes)
